### ISSUE TITLE
PG::UndefinedFunction: ERROR:  operator does not exist: bytea facet.& bytea

### ISSUE THREAD

**Issue by jamiefolsom** [hyperstudio/repertoire-faceting#6]
Hey @christopheryork -- I am currently seeing this in the logs on requests for pages with faceting installed all new deployments on Heroku (eg staging, review apps, etc).

See: http://cfrp-staging-pr-5.herokuapp.com/registers

```
ActiveRecord::StatementInvalid (PG::UndefinedFunction: ERROR:  operator does not exist: bytea facet.& bytea
LINE 1: ... fct.parterre_receipts, facet.count(fct.signature OPERATOR(f...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
SELECT fct.total_receipts, facet.count(fct.signature OPERATOR(facet.&) mask.signature) FROM (SELECT "facet"."registers_total_receipts_index"."total_receipts", "facet"."registers_total_receipts_index"."signature" FROM "facet"."registers_total_receipts_index" ) AS fct , (SELECT ((SELECT facet.signature(registers._packed_id) FROM "registers"  WHERE "registers"."verification_state_id" IN (1, 6))) AS signature) AS mask ORDER BY total_receipts ):
```

PostgreSQL has been upgraded to 9.6.1 on that platform, which perhaps is a bit (no pun intended) stricter about type checking?

Just documenting this -- not sure if you have time to have a look, or offer hints. Happy to work on it, but if you have any thoughts...

[Update] It's not the version of Postgres. See below. Faceting works on staging, not on the review app, but they're both using 9.6.1

**Comment by christopheryork** [comment]
Hi @jamiefolsom!  This looks like a PostgreSQL schema problem to me.

The query is looking for an operator in the 'facet' schema (so, named 'facet.&').  This is correct -
 all the facet indices and the faceting API binding functions are kept in this schema, so it's easy to remove faceting from an application in one fell swoop.

I looked in the production database, and it has the '&' operator but in the schema 'public' instead of 'facet' (i.e. at 'public.&').  So it appears the facet functions got loaded into the wrong schema at some point - perhaps during a failed migration, or as a side effect of Heroku's PostgreSQL update?

The following Rails console code (or similar) should get you back to normal.  It backs out of faceting and then re-installs (for Heroku hosts only - it's basically the standard migration at https://github.com/hyperstudio/repertoire-faceting-example/blob/0cc1dffc0087c8c2958b12b2a07b2b29f22e187a/db/migrate/20101028165208_install_faceting.rb):

on production:

```
heroku run bundle exec rails console --app cfrp
> conn = ActiveRecord::Base.connection
> conn.execute( 'DROP SCHEMA facet CASCADE' )
> conn.execute( 'CREATE SCHEMA facet' )
> conn.execute( conn.faceting_api_sql(:bytea, 'facet') )    # NB this sets the schema name!
> Register.index_facets(Register.facet_names)                  # Index every possible facet...
> Play.index_facets(Play.facet_names)
```

on development, it's a bit simpler:

psql cfrp_development
> DROP EXTENSION faceting CASCADE
> CREATE EXTENSION faceting
bundle exec rails console
> Register.index_facets(Register.facet_names)
> Play.index_facets(Play.facet_names)

The pain point here is that we can't just use the standard PostgreSQL extension on Heroku, so must dance around their limitations by using an alternate API binding.

Hope that helps!  Best, Christopher

**Comment by jamiefolsom** [comment]
Thanks @christopheryork, this is helpful. I see what you're saying about the & operator being on the wrong schema, which is true both on production and on staging. What's odd, though, is that the faceted browser is working on both of those instances of the application. See: [staging](http://cfrp-staging.herokuapp.com/registers) and [production](http://app.cfregisters.org/registers). I was seeing the error on a copy of the staging app.

**Comment by christopheryork** [comment]
Hmm...  I see your point.  Could you post the complete SQL query that is failing?

**Comment by jamiefolsom** [comment]
Sure, it appears to be this one:

```SQL
SELECT fct.parterre_receipts, facet.count(fct.signature OPERATOR(facet.&) mask.signature) FROM 
	(SELECT "facet"."registers_parterre_receipts_index"."parterre_receipts", "facet"."registers_parterre_receipts_index"."signature" FROM "facet"."registers_parterre_receipts_index" ) AS fct , 
	(SELECT ((SELECT facet.signature(registers._packed_id) FROM "registers"  WHERE "registers"."verification_state_id" IN (1, 6))) AS signature) AS mask 
ORDER BY parterre_receipts
```

**Comment by jamiefolsom** [comment]
Here's another:

```SQL
SELECT fct.title1, facet.count(fct.signature OPERATOR(facet.&) mask.signature) FROM 
    (SELECT "facet"."registers_title1_index"."title1", "facet"."registers_title1_index"."signature" FROM "facet"."registers_title1_index" ) AS fct , 
    (SELECT ((SELECT facet.signature(registers._packed_id) FROM "registers"  WHERE "registers"."verification_state_id" IN (1, 6))) AS signature) AS mask 
ORDER BY count DESC, title1 ASC
```

**Comment by jamiefolsom** [comment]
I've spun up a copy of staging too. Here's a link: https://cfrp-staging-pr-6.herokuapp.com/registers

**Comment by christopheryork** [comment]
Several things...

(a) When creating a Heroku follower database, the javascript (plv8) functions are not moving over.  This is why you are getting errors.  In Heroku, plv8 requires a non-hobby account.  Any chance you used a hobby account for the follower DB?

(b) The query runs on staging & production because the faceting module is actually (correctly) loaded into the 'facet' schema after all.  Due to PostgreSQL's search path logic, some bits of it are being obscured by identical functions loaded into 'public'.

(c) So a bit of clean up in 'public' is still required, to avoid future confusion and potential version errors.  It's quite simple: ping me later and I'll describe what to clean out.

**Comment by jamiefolsom** [comment]
@christopheryork this makes sense. Yes, "review apps" (created to review github pull requests, as a copy of the application with data pulled from staging, and code pulled from the PR) use the cheapest resources they can by default. I believe I can override that in the app.json config, but we'll see. 

Is plv8 installed by a rake task or migration, or via configuration or a script invoked at the command line? 

Thanks!

**Comment by christopheryork** [comment]
Heroku relies on pg_dump to create follower databases, so if the master DB uses plv8, the dump will include a corresponding command to install it.  You do need proper permissions to restore the DB backup on the follower though.

I'm surprised Heroku silently ignores errors creating followers but... ah well.  Presumably using a non-hobby Heroku account for them is all that's necessary.

FYI Ultimately plv8 is installed [here](https://github.com/hyperstudio/repertoire-faceting/blob/3c7dfafc385a7d47c4615ce83d042fe8130c662d/ext/bytea/bytea.sql#L18), which gets sourced in the [migration that installs faceting](https://github.com/hyperstudio/repertoire-faceting-example/blob/0cc1dffc0087c8c2958b12b2a07b2b29f22e187a/db/migrate/20101028165208_install_faceting.rb#L30).

**Comment by jamiefolsom** [comment]
For the record, some Heroku config arcana. Heroku offers the option to specify a particular add on tier or plan for each add on specified in the app.json, which is the config file which is used to create review apps from github pull requests. However, for some reason, they disabled the option to specify the non-default tier (the cheapest) on the CFRP heroku team, if not for all non-owner members of a team or application. I requested that option be re-enabled, and once it was, the platform used the non-hobby postgres add on tier specified in the app.json, and we now have plv8 available on review apps again. Sheesh. Thanks for your help with this, @christopheryork!

**Comment by christopheryork** [comment]
What a runaround!  Thanks for the update.  C
